# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoMVVM
pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'ObjectMapper'
pod 'MBProgressHUD'
pod 'MKProgress'
pod 'NSObject+Rx'
pod 'Reusable'
pod 'MJRefresh'
pod 'Then'
pod 'OrderedSet'
end
